-- The Abbreviated file is available in ASCII (ISO/IEC 8859-1) format and as a Microsoft Excel spreadsheet.
-- It contains all the food items found in the relational database, but with fewer nutrients and other
-- related information. The abbreviated file does not include values for starch, fluoride, betaine,
-- vitamin D2 and D3, added vitamin E, added vitamin B12, alcohol, caffeine, theobromine, phytosterols,
-- individual amino acids, individual fatty acids, or sugars.
CREATE TABLE ABBREV
(
  NDB_NO      CHAR(5) PRIMARY KEY NOT NULL,
  SHRT_DESC   VARCHAR(60)         NOT NULL,
  WATER       DOUBLE,
  ENERG_KCAL  INTEGER,
  PROTEIN     DOUBLE,
  LIPID_TOT   DOUBLE,
  ASH         DOUBLE,
  CARBOHYDRT  DOUBLE              NOT NULL,
  FIBER_TD    DOUBLE,
  SUGAR_TOT   DOUBLE,
  CALCIUM     INTEGER,
  IRON        DOUBLE,
  MAGNESIUM   INTEGER,
  PHOSPHORUS  INTEGER,
  POTASSIUM   INTEGER,
  SODIUM      INTEGER,
  ZINC        DOUBLE,
  COPPER      DOUBLE,
  MANGANESE   DOUBLE,
  SELENIUM    DOUBLE,
  VIT_C       DOUBLE,
  THIAMIN     DOUBLE,
  RIBOFLAVIN  DOUBLE,
  NIACIN      DOUBLE,
  PANTO_ACID  DOUBLE,
  VIT_B6      DOUBLE,
  FOLATE_TOT  INTEGER,
  FOLIC_ACID  INTEGER,
  FOOD_FOLATE INTEGER,
  FOLATE_DFE  INTEGER,
  CHOLINE_TOT DOUBLE,
  VIT_B12     DOUBLE,
  VIT_A_IU    INTEGER,
  VIT_A_RAE   INTEGER,
  RETINOL     INTEGER,
  ALPHA_CAROT INTEGER,
  BETA_CAROT  INTEGER,
  BETA_CRYPT  INTEGER,
  LYCOPENE    INTEGER,
  "LUT+ZEA"   INTEGER,
  VIT_E       DOUBLE,
  VIT_D_MCG   DOUBLE,
  VIT_D_IU    INTEGER,
  VIT_K       DOUBLE,
  FA_SAT      DOUBLE,
  FA_MONO     DOUBLE,
  FA_POLY     DOUBLE,
  CHOLESTRL   DOUBLE,
  GMWT_1      DOUBLE,
  GMWT_DESC1  VARCHAR(120),
  GMWT_2      DOUBLE,
  GWT_DESC2   VARCHAR(120),
  REFUSE_PCT  INTEGER
)
